=== Migdrago/proyectofinal-miguel-gimansio/lenguajemarcas/gimnasio.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="gimnasio">
    <xs:complexType>
    <xs:sequence>

        <xs:element name="clientes">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">                    <xs:complexType>
                <xs:sequence>
                <xs:element name="id" type="xs:int"/>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>                    <xs:element name="telefono" type="xs:string"/>
                </xs:sequence>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
            </xs:complexType>
        </xs:element>

        <xs:element name="clases">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="clase" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>                    <xs:element name="id" type="xs:int"/>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="horario" type="xs:string"/>                        </xs:sequence>
                </xs:complexType>
            </xs:element>
            </xs:sequence>
            </xs:complexType>
            </xs:element>

    </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Migdrago/proyectofinal-miguel-gimansio/lenguajemarcas/gimnasio.xml
<?xml version="1.0" encoding="UTF-8"?>

<gimnasio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="gimnasio.xsd">

    <clientes>
        <cliente>
            <id>1</id>
            <nombre>Juan Pérez</nombre>
            <email>juan@email.com</email>
            <telefono>123456789</telefono>
        </cliente>

        <cliente>
            <id>2</id>
            <nombre>Ana López</nombre>
            <email>ana@email.com</email>
            <telefono>987654321</telefono>
        </cliente>
    </clientes>

    <clases>
        <clase>
            <id>1</id>
            <nombre>Spinning</nombre>
            <horario>10:00</horario>
        </clase>

        <clase>
            <id>2</id>
            <nombre>Yoga</nombre>
            <horario>18:00</horario>
        </clase>
    </clases>

</gimnasio>
